### ISSUE TITLE
Can more people multiply than can count?

### ISSUE THREAD

**Issue by pjbull** [drivendataorg/cgap-fii#16]
Unintuitive examples in the interactive vid.

**Comment by ejm714** [comment]
For MMR, there are 6463 who can multiply but can't count. This is not a result of NAs as the can_count and can_multiply variables don't originally include any NAs.

**Comment by pjbull** [comment]
```
can_count	0.0	1.0
can_multiply		
0.0	17109	15516
1.0	26819	180556
```

**Comment by ejm714** [comment]
@pjbull so apparently the answer is yes, many people can multiply but not count ❓ 🤷‍♀️
