### ISSUE TITLE
Replace Financial Health slide with different question

### ISSUE THREAD

**Issue by pjbull** [drivendataorg/cgap-fii#23]
Slide 14, "Financial Health" should be swapped for FL6_1 and/or FL6_4

**Comment by ejm714** [comment]
FL6_1, FL6_4

**Comment by ejm714** [comment]
@pjbull two new maps are currently in appendix for review as to which one gets swapped into the main deck

**Comment by pjbull** [comment]
@ejm714 :bow: great!
