### ISSUE TITLE
Smartphone Penetration does not match Average Phone Sophistication

### ISSUE THREAD

**Issue by pjbull** [drivendataorg/cgap-fii#25]
Slides 17 (Smartphone Penetration) and Slide 18 (Mobile Phone Technology) do not necessarily match up (average sophistication seems lower than expected given the smartphone penetration).

Is this based on how these are calculated, and do those calculations make sense?

**Comment by ejm714** [comment]
Treatment of null values is correct, replace map in slides w/ median to be more interpretable
